//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloWorld.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int Id { get; set; }
        public int FirstPlayerId { get; set; }
        public int SecondPlayerId { get; set; }
        public int FirstPlayerPoints { get; set; }
        public int SecondPlayerPoints { get; set; }
        public int GameQuestionsId { get; set; }
        public System.DateTime DatePlayed { get; set; }
        public string FirstPlayerAnswer { get; set; }
        public string SecondPlayerAnswer { get; set; }
    
        public virtual GameQuestions GameQuestions { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
