//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloWorld.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Practise
    {
        public int Id { get; set; }
        public int Category { get; set; }
        public int UserId { get; set; }
        public int Points { get; set; }
        public System.DateTime DatePlayed { get; set; }
        public HelloWorld.Common.Enums.QuestionLevel Level { get; set; }
    
        public virtual User User { get; set; }
    }
}
